# Generated by Django 2.2.6 on 2019-12-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('imageUrl', models.CharField(max_length=200)),
                ('siteName', models.CharField(max_length=100)),
                ('primaryCategory', models.CharField(max_length=100)),
            ],
        ),
    ]
