# Generated by Django 2.2.6 on 2019-12-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealsengine', '0002_deallink_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deallink',
            name='offerId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='deallink',
            unique_together={('siteName', 'offerId')},
        ),
    ]
