# Generated by Django 2.2.6 on 2019-12-30 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dealsengine', '0005_auto_20191230_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deallink',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='deallink',
            old_name='importDate',
            new_name='import_date',
        ),
        migrations.RenameField(
            model_name='deallink',
            old_name='linkPostDate',
            new_name='link_post_date',
        ),
        migrations.RenameField(
            model_name='deallink',
            old_name='offerId',
            new_name='offer_id',
        ),
        migrations.RenameField(
            model_name='deallink',
            old_name='primaryCategory',
            new_name='primary_category',
        ),
        migrations.RenameField(
            model_name='deallink',
            old_name='siteId',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='deallink',
            old_name='description',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='dealsite',
            old_name='crawlIntervalMins',
            new_name='crawl_interval_mins',
        ),
        migrations.RenameField(
            model_name='dealsite',
            old_name='primaryCrawlUrl',
            new_name='primary_crawl_url',
        ),
        migrations.RenameField(
            model_name='dealsite',
            old_name='siteName',
            new_name='site_name',
        ),
        migrations.AddField(
            model_name='deallink',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='deallink',
            unique_together={('site', 'offer_id')},
        ),
    ]
