# Generated by Django 2.2.6 on 2020-01-02 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealsengine', '0008_auto_20200101_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealsengine.DealLink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_clicks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
