# Generated by Django 2.2.6 on 2020-01-02 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealsengine', '0010_auto_20200102_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkclick',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_clicks', to=settings.AUTH_USER_MODEL),
        ),
    ]
