# Generated by Django 2.2.6 on 2020-01-09 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dealsengine', '0013_threadtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='deallink',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deallink',
            name='import_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='deallink',
            index=models.Index(fields=['import_date', 'score'], name='dealsengine_import__193784_idx'),
        ),
    ]
