# Generated by Django 2.2.6 on 2020-01-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealsengine', '0014_auto_20200108_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deallink',
            name='link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='deallink',
            name='sub_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='deallink',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
