# Generated by Django 2.2.6 on 2020-01-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealsengine', '0015_auto_20200108_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='deallink',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
