# Generated by Django 2.2.6 on 2020-01-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealsengine', '0017_auto_20200112_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deallink',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
