# Generated by Django 2.2.6 on 2020-01-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealsengine', '0018_auto_20200112_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deallink',
            name='image_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='deallink',
            name='offer_id',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='deallink',
            name='primary_category',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
